<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:macro name="chassis_visual">
        <visual>
            <origin xyz="${-body_reference_x} 0 ${chassis_height-aabb_height/2}"
                rpy="0 0 ${M_PI/2.0}" />
            <geometry>
                <mesh filename="package://robucar_description/meshes/chassis.dae" />
            </geometry>
        </visual>
    </xacro:macro>


</robot>