/mobile_base_controller:
  ros__parameters:
    controller:
      base_frame_id: base_link
      odom_frame_id: odom
      enable_odom_tf: false
      publish_rate: 50.0
      timeout: 0.5
#      joints_prefix:
#      command_limits:
#        minimal_longitudinal_speed:
#        maximal_longitudinal_speed:
#        maximal_angular_speed:
    base_info:
      geometry:
        axles_distance: 1.38
        front_axle:
          wheels_distance: 0.89
          wheels:
            radius: 0.325
            width: 0.13
            hub_carrier_offset: 0.148
        rear_axle:
          wheels_distance: 0.89
          wheels:
            radius: 0.325
            width: 0.13
            hub_carrier_offset: 0.148
        aabb:
          length: 2.3490
          width: 0.7000
          height: 1.1330
          center: [0., 0., 0.71650]
        ground_clearance: 0.15

      wheels_steering_control:
         command:
           maximal_angle: 0.48450
           maximal_angular_speed: 1.0
         sensor:
           angle_std: 0.017453
           angle_range: 0.78540

      wheels_speed_control:
         command:
           maximal_speed: 2.0
           maximal_acceleration: 1.0
         sensor:
           speed_std: 0.1
           speed_range: 2.0

      inertia:
        mass: 340.
        center: [0., 0., 0.71650]
        z_moment: 239.

      control_point : [-0.69, 0.0, 0.0]

      joints:
        base_footprint_joint_name : base_footprint
        inertial_joint_name: inertial_joint
        front_left_wheel_steering_joint_name: front_left_wheel_steering_joint
        front_right_wheel_steering_joint_name: front_right_wheel_steering_joint
        rear_left_wheel_steering_joint_name: rear_left_wheel_steering_joint
        rear_right_wheel_steering_joint_name: rear_right_wheel_steering_joint
        front_left_wheel_spinning_joint_name: front_left_wheel_spinning_joint
        front_right_wheel_spinning_joint_name: front_right_wheel_spinning_joint
        rear_left_wheel_spinning_joint_name: rear_left_wheel_spinning_joint
        rear_right_wheel_spinning_joint_name: rear_right_wheel_spinning_joint

      links:
        base_link_name: base_link
        base_footprint_link_name: base_footprint
        inertial_link_name: inertial_link
        front_left_wheel_steering_link_name: front_left_wheel_steering_link
        front_right_wheel_steering_link_name: front_right_wheel_steering_link
        rear_left_wheel_steering_link_name: rear_left_wheel_steering_link
        rear_right_wheel_steering_link_name: rear_right_wheel_steering_link
        front_left_wheel_spinning_link_name: front_left_wheel_spinning_link
        front_right_wheel_spinning_link_name: front_right_wheel_spinning_link
        rear_left_wheel_spinning_link_name: rear_left_wheel_spinning_link
        rear_right_wheel_spinning_link_name: rear_right_wheel_spinning_link



