/**:
  ros__parameters:
    base_info:
      geometry:
        axles_distance: 1.2
        front_axle:
          wheels_distance: 0.9
          wheels:
            radius: 0.28
            width: 0.1
            hub_carrier_offset: 0.1
        rear_axle:
          wheels_distance: 0.9
          wheels:
            radius: 0.28
            width: 0.1
            hub_carrier_offset: 0.1
        aabb:
          length: 1.66000
          width: 0.60000
          height: 0.66000
          center: [0., 0., 0.42]
        ground_clearance: 0.19

      axles_steering_control:
         command:
           maximal_angle: 0.2
           maximal_angular_speed: 1.0
         sensor:
           angle_std: 0.017453
           angle_range: 0.26180

      wheels_speed_control:
         command:
           maximal_speed: 2.0
           maximal_acceleration: 1.0
         sensor:
           speed_std: 0.1
           speed_range: 2.0

      inertia:
        mass: 350.
        center: [0., 0., 0.42]
        z_moment: 156.

      control_point : [-0.6, 0.0, 0.0]

      joints:
        base_footprint_joint_name : base_footprint
        inertial_joint_name: inertial_joint
        front_axle_steering_joint_name: front_axle_steering_joint
        rear_axle_steering_joint_name: rear_axle_steering_joint
        front_left_wheel_steering_joint_name: front_left_wheel_steering_joint
        front_right_wheel_steering_joint_name: front_right_wheel_steering_joint
        rear_left_wheel_steering_joint_name: rear_left_wheel_steering_joint
        rear_right_wheel_steering_joint_name: rear_right_wheel_steering_joint
        front_left_wheel_spinning_joint_name: front_left_wheel_spinning_joint
        front_right_wheel_spinning_joint_name: front_right_wheel_spinning_joint
        rear_left_wheel_spinning_joint_name: rear_left_wheel_spinning_joint
        rear_right_wheel_spinning_joint_name: rear_right_wheel_spinning_joint

      links:
        base_link_name: base_link
        base_footprint_link_name: base_footprint
        inertial_link_name: inertial_link
        front_axle_steering_link_name: front_axle_steering_link
        rear_axle_steering_link_name: rear_axle_steering_link
        front_left_wheel_steering_link_name: front_left_wheel_steering_link
        front_right_wheel_steering_link_name: front_right_wheel_steering_link
        rear_left_wheel_steering_link_name: rear_left_wheel_steering_link
        rear_right_wheel_steering_link_name: rear_right_wheel_steering_link
        front_left_wheel_spinning_link_name: front_left_wheel_spinning_link
        front_right_wheel_spinning_link_name: front_right_wheel_spinning_link
        rear_left_wheel_spinning_link_name: rear_left_wheel_spinning_link
        rear_right_wheel_spinning_link_name: rear_right_wheel_spinning_link

